"""initial users + thread_metadata ORM management

Revision ID: 603868767db0
Revises: da1ba1d69b94
Create Date: 2026-03-11 14:04:36.128370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603868767db0'
down_revision: Union[str, Sequence[str], None] = 'da1ba1d69b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_thread_metadata_created_at'))
        batch_op.create_index('idx_thread_metadata_created_at', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_thread_metadata_created_at', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
        batch_op.create_index(batch_op.f('idx_thread_metadata_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###
